### ISSUE TITLE
VB.NET

### ISSUE THREAD

**Issue by saed23** [fstandhartinger/LightGbmDotNet#1]
Hi,
Is it possible to use this library with VB.NET? If so, how?
Thanks,
Saed

**Comment by fstandhartinger** [comment]
Hi Saed,
sure, you can just 
- compile the LightGbmDotNet project and then 
- open your VB.NET project
- add a reference to the LightGbmDotNet.dll assembly
- now you can create instances of the LightGbm class and call its Train and Predict methods

Best regards
Florian

**Comment by saed23** [comment]
Thank you so much, Florian.
Saed

**Comment by fstandhartinger** [comment]
You're welcome, Saed! :)

**Comment by saed23** [comment]
I'm sorry for bothering you again. I successfully compiled the code but I
am trying to find a script to read a text file directly as of type
IEnumerable<IEnumerable<double>> with no success. I really appreciate if
you could provide me a sample code.

Best,
Saed

**Comment by fstandhartinger** [comment]
Hi Saed,

I am not exactly familiar with VB.NET, but maybe this might help you:
https://stackoverflow.com/questions/5777038/vb-net-reading-a-csv-file-into-a-2d-array
Or this:
https://social.msdn.microsoft.com/Forums/en-US/7b0e28b4-c1ef-49d6-8f46-11b379428052/import-from-csv-file-to-two-dimensional-array?forum=vbgeneral

You might need to add double.Parse calls when reading the data from the file to make sure it becomes an enumerable of doubles, not strings or anything else.

Best regards 
Florian

**Comment by saed23** [comment]
Hi Florian,

Thank you for your prompt response.

All the best,
Saed
